version: '3.7'
services:
  nodejs-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3081:3081"
    container_name: zeplin-case-api
    links:
      - mongo-db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db